### ISSUE TITLE
Cache is reporting wrong OS Architecture for Windows Players

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-cache-v2#66]
<b>How it works now:</b>
Look at Displays PZ4ABCDYJH52 which is a 64 Bit OS. Notice that it is reported as a 32 Bit OS:
![2016-10-26_13-30-40](https://cloud.githubusercontent.com/assets/6862256/19737557/f33e4eac-9b81-11e6-8376-e8d7adb78220.png)

<b>How it should work:</b>
It should report back the correct OS architecture.

**Comment by alanclayton** [comment]
This issue is fixed.
