### ISSUE TITLE
Images that are replaced in storage still show in preview and player

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-cache-v2#73]
**How it works now**

If you replace an image file in storage with a file of the same name (e.g. image-1.png) the older file will still show in preview and the player unless you manually clear the browser cache or restart the player. This occurs after the 20min refresh rate set in Rise Cache. 

**How it should work**

When an image is moved to trash and a new image with the same name is uploaded the older image should be eventually be replaced in preview and on the display without manually having to clear the browser cache or refresh the display.

I have set up a test display here that shows one imagehttps://apps.risevision.com/editor/workspace/cc925e48-3f4b-43ac-9e7f-ad07d987053a/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

Although the red image is currently in storage, the blue image is still shown. Both are named image-1.png. 

File shown in editor, preview and player:
<img width="605" alt="screen shot 2016-12-16 at 5 50 33 pm" src="https://cloud.githubusercontent.com/assets/8008948/21281082/39297bc2-c3b8-11e6-9c5b-7b5edc1f1a99.png">

Actual file in storage:
<img width="336" alt="screen shot 2016-12-16 at 5 50 49 pm" src="https://cloud.githubusercontent.com/assets/8008948/21281099/49dfde98-c3b8-11e6-8803-2b51596de20d.png">

Thanks!

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 73](https://trello.com/c/jME4kBeG/2893-1-issue-73)

**Comment by robb-price** [comment]
@rodrigopavezi I just tried testing this with my test Company, and when using that URL (http://s3.amazonaws.com/widget-image-test/stage-0-dev/0.1.1/dist/widget.html), it tells me that the Company does not have a valid subscription, or the folder has been moved to the Trash, neither of which are true.

Here is the Presentation I am usingL https://apps.risevision.com/editor/workspace/10f6b1a0-3fb0-451f-8f96-5b627fab821e//htmleditor?cid=556323b8-984c-4127-aa08-4d73d019bcb8

**Comment by robb-price** [comment]
@rodrigopavezi Using this Presentation: http://rva.risevision.com/#/PRESENTATION_MANAGE/id=10f6b1a0-3fb0-451f-8f96-5b627fab821e?cid=556323b8-984c-4127-aa08-4d73d019bcb8, the image does not automatically update on the Display. I gave it one hour, and it never updated.

After I save and publish the Presentation, it updates, but that should not be necessary, it should do it without requiring Saving and Publishing the Presentation.

Can you investigate and let me know once this is corrected?

Thanks!

**Comment by robb-price** [comment]
Verified and closed, however this still happens with Folders. That bug is logged here: https://github.com/Rise-Vision/rise-cache-v2/issues/75
