### ISSUE TITLE
SVG's are not showing up reliably in a Presentation on a Display

### ISSUE THREAD

**Issue by donnapep** [Rise-Vision/rise-cache-v2#74]
<b>How it works now:</b>
1. Put <a href="https://apps.risevision.com/editor/workspace/bfd86f2c-1430-49b5-875c-6c541a7e7eb1/?cid=556323b8-984c-4127-aa08-4d73d019bcb8">this Presentation</a> into a Schedule, and play it on a Display. Notice that sometimes the svg logo at the top of the Presentation sometimes shows, and sometimes does not show. The best way to make it stop showing is to add a second Presentation to the Schedule.

The Network tab of Dev Tools looks correct, it is calling the svg file from the cache, it just doesn't show up on screen.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 23 - SVG images don't work reliably.](https://trello.com/c/NbHjBXqR/2904-1-issue-23-svg-images-don-t-work-reliably)

**Comment by robb-price** [comment]
@donnapep Followed your recommendations and it worked like a charm. Thanks!
