### ISSUE TITLE
If you have a folder with 1 image and update it with another identically named image, it still shows the old version in preview and on Player

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-cache-v2#75]
<b>How it works now</b>

1. Add an image from a Folder in Storage to your Presentation with the Image Widget. Make sure there is only <b>ONE</b> image in this folder.
2. Replace the image file in storage with a file of the same name, and notice that the older file will still show in preview and the player unless you manually clear the browser cache or restart the player. This occurs after the 20min refresh rate set in Rise Cache.

<b>How it should work:</b>

The image should update to the new version automatically within 20 minutes.

Presentation to test with: https://apps.risevision.com/editor/workspace/10f6b1a0-3fb0-451f-8f96-5b627fab821e/?cid=556323b8-984c-4127-aa08-4d73d019bcb8 (This Presentation is using the updated test version of the Image Widget : http://s3.amazonaws.com/widget-image-test/stage-0/0.1.1/dist/widget.html)

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 75 - Images in Folders that are replaced continue showing the older version.](https://trello.com/c/t4wnUZjh/2920-1-issue-75-images-in-folders-that-are-replaced-continue-showing-the-older-version)

**Comment by robb-price** [comment]
@stulees Updated the bug description to indicate that this only happens when there is 1 image in the folder.

**Comment by stulees** [comment]
@robb-price Closing this issue as it's an issue with Image Widget not Rise Cache. Issue now here - https://github.com/Rise-Vision/widget-image/issues/113
